name: MCRealisticPlus
main: com.SamB440.Main
author: SamB440
authors: [c0mputex, CitadelCraft, markrasher123, zackerykr & AssassinsKeeper, CheB440, Chazmondo]
website: http://www.islandearth.net
depend: [WorldGuard]
version: ALPHA 1.5.9
commands:
  MCRealistic: 
     description: MCRealistic commands
     usage: /MCRealistic
     aliases: [mcr, mcreal, mcrc]
  MyStats:
     description: MCRealistic stats
     usage: /MyStats
  Fatigue:
     description: MCRealistic fatigue
     usage: /Fatigue
  Thirst:
     description: MCRealistic thirst
     usage: /Thirst
